### ISSUE TITLE
Add Support for Parsing Dynamic SQL

### ISSUE THREAD

**Issue by nathan-boyd** [tsqllint/tsqllint#106]
This feature would attempt to parse all strings in sql scripts, and if possible apply rules.

Open to feedback, but starting with the following requirements:
- Parsing shall descend no more than one level. No support for dynamic SQL within dynamic SQL.
- Error reporting will occur with line numbers and columns relative to the parent script
  - If an error occurs on line 5 of the dynamic SQL but on line 50 of the script then line 50 will be reported.

**Comment by dougwilson** [comment]
I'm sure this will be tricky, especially around trying to figure out what the completed string value is. I can see the value, though.

Thoughts on what kind of constraints you're thinking of for the first iteration?

**Comment by geoffbaker** [comment]
Based on what I did before you're going to also have to figure out a string
is SQL in the first place and then how to combine multiple string values
together to get the SQL statement handling variables and other functions in
the middle of the SQL statements.

Also you maybe bit by the nesting issue that I was - meaning you start with
one string and keep going till X to parse as one item. However, each thing
after X is also visited for which you really don't want to process twice.

GEOFF BAKER (GEO)
Principal Architect Engineer | Salesforce Marketing Cloud
<http://www.exacttarget.com/>
Mobile: 317-331-1185

<http://www.salesforce.com/signature>
--

**Comment by nathan-boyd** [comment]
@dougwilson a good initial constraint might be to guard against what @geoffbaker brings to light. supporting the creation of valid sql from the concatenation of one or more strings is much more challenging than parsing a single string. 

that asks the question though, is there value add from parsing that simple case? is parsing a single string a value add, or do we nearly always have to concat strings together to build strings?
