### ISSUE TITLE
Visual Studio Extension

### ISSUE THREAD

**Issue by ostreifel** [tsqllint/tsqllint#116]
Are there any plans to make this available as an extension for visual studio?

**Comment by nathan-boyd** [comment]
Thanks for your interest in TSQLLINT. Yes there are absolutely plans to create a VS extension, I haven't prioritized the work yet but will do so now that someone has expressed interest.l

**Comment by ostreifel** [comment]
Btw I found this repo while doing research for a [vscode implementation](https://github.com/ostreifel/vscode-tsql-lint) for tsql files. As vscode extensions are ts/js and this repo is C# code sharing may just be limited to code porting. 

My extension right now is super basic as its very new right now.

**Comment by nathan-boyd** [comment]
@ostreifel resolved with: https://marketplace.visualstudio.com/items?itemName=tsqllint.tsqllint
