### ISSUE TITLE
running 'tsqllint -i .' executes a lint rather than a simple init

### ISSUE THREAD

**Issue by ostreifel** [tsqllint/tsqllint#136]
Initially I ran 
```
tsqllint -i
```
Generated a config file in my user directory rather than in the git repo
```
tsqllint -i .
```
Runs lint for the current directory. In my case this meant it ran for 1-2 minutes before I just killed the process.

**Comment by nathan-boyd** [comment]
I wasn't able to reproduce this behavior in osx or win.

**Comment by ostreifel** [comment]
[examples.zip](https://github.com/tsqllint/tsqllint/files/1661039/examples.zip)
Unzip and cd to examples
run
```
tsqllint -i .
```
This will generate a ton of error messages even though only an init was requested.

**Comment by nathan-boyd** [comment]
in progress

**Comment by nathan-boyd** [comment]
resolved in #182
