### ISSUE TITLE
TSqlLint fails (report errors) even is disabled in 1st line by  /* tsqllint-disable */ if file contain "\" (backslash) symbol

### ISSUE THREAD

**Issue by svasilenko** [tsqllint/tsqllint#152]
Got issue linting file for SQLPlus. Linting is disabled by /* tsqllint-disable */.  File body is

`/* tsqllint-disable */`
`@@Scripts\dfu_setutp_import_cleanup.sql`

Loaded plugin 'TSQLLint_MC_Plugin.MCPlugin'
TSqlLintIssue.sql(-1,-1): error set-ansi : Expected SET ANSI_NULLS ON near top of file.
TSqlLintIssue.sql(-1,-1): error set-nocount : Expected SET NOCOUNT ON near top of file.
TSqlLintIssue.sql(-1,-1): error set-quoted-identifier : Expected SET QUOTED_IDENTIFIER ON near top of file.
D:\__scripts\TSqlLint\TSqlLintIssue.sql(-1,-1): error set-transaction-isolation-level : Expected SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED near top of file.

Linted 1 files in 0.2491611 seconds

4 Errors.
0 Warnings

PS D:\__scripts\TSqlLint> tsqllint -v
Loaded plugin 'TSQLLint_MC_Plugin.MCPlugin'
v1.9.2.0
PS D:\__scripts\TSqlLint>

removed `@@` - got the same issue
removed `Scripts\` - done without issues with 0 errors and 0 warnings

**Comment by nathan-boyd** [comment]
resolved in 6f45e340a8530e66b2fbcbb8e16ef884ea8021cb
