### ISSUE TITLE
DROP IF EXISTS syntax doesn't appear to be supported

### ISSUE THREAD

**Issue by matt-s-wise** [tsqllint/tsqllint#165]
SQL Server 2016 introduced DROP [VIEW|TABLE|PROCEDURE|FUNCTION] IF EXISTS syntax.
TSqlLint is reporting these as syntax errors i.e.:
`NoticesView.sql(1,11): error invalid-syntax : Incorrect syntax near IF..`
and this isn't configurable via the rules.
It looks like the TSqlLint tool uses the Microsoft.SqlServer.TransactSql.ScriptDom package so it might be that this cannot actually be solved without Microsoft updating their package unfortunately, and I'm not sure that is even still maintained...

**Comment by dougwilson** [comment]
Yes, the parsing is indeed done by the Microsoft.SqlServer.TransactSql.ScriptDom package. It was last updated 4 months ago which doesn't seem unmaintained to me. We could move if it is. Can you clarify how you came to the conclusion that the Microsoft.SqlServer.TransactSql.ScriptDom package is unmaintained?

**Comment by nathan-boyd** [comment]
DROP if exists is a feature that is enabled compatibility level 130, TSQLLint currently operates at 120. Our oldest feature request #3 is for a configurable parser, its probably time to prioritize that.

**Comment by nathan-boyd** [comment]
Resolved in #166, this will be released to a new NPM package sometime today.

**Comment by matt-s-wise** [comment]
Hi, very much appreciate you putting in the work to implement the configurable parser feature! Myself and a colleague had identified that TSql120Parser was being instantiated in FragmentBuilder; we downloaded your source code, saw that there was a TSql140Parser class as well, rebuilt with that change, and it worked for us... I was about to reply on this thread to suggest this but you fixed it already :-)
Just wondering if there is a reason why your compatibility level list only covers up to 130 and not 140 (although this should be fine for us since that 130 = SQL Server 2016 I believe)?

**Comment by nathan-boyd** [comment]
140 (sql server 2017) was not intentionally left out, I just pulled the levels from an out of date chart. 140 should be supported as well, #172 for tracking.

I very much appreciate you bringing this to our attention!
