### ISSUE TITLE
.tsqllintrc documentation seems a little out of step with the actual set of implemented rules

### ISSUE THREAD

**Issue by matt-s-wise** [tsqllint/tsqllint#180]
Not sure that the documentation for the .tsqllintrc file in the README, has been kept up to date with the actual rule classes that have been implemented.
E.g.
* concat-strings is mentioned but isn't referenced anywhere the source code
* there is a NamedContraintRule class whose "named-constraint" rule key isn't listed
* there is a UnicodeStringRule class whose "unicode-string" rule key isn't listed

There may be other discrepancies.

**Comment by nathan-boyd** [comment]
resolved in be437b9
