### ISSUE TITLE
Custom plugin violations not ordered ascending

### ISSUE THREAD

**Issue by esauser** [tsqllint/tsqllint#204]
Custom plugin violations are not ordered ascending in the output.  Instead, they are ordered in reverse order that they are reported.  Technically, this could be worked around by storing them within the plugin and then reporting them in reverse order there, but it seems the burden for that shouldn't fall on the plugin.
![image](https://user-images.githubusercontent.com/24945592/50066904-f4263900-0183-11e9-8adb-35a688422e2f.png)

**Comment by esauser** [comment]
Why is this being marked stale?

**Comment by LowlyDBA** [comment]
@esauser Its just a bot that operates on issues not touched for xx days. Commenting like you did can remove the label (as seen above) - it is nothing personal :)
