### ISSUE TITLE
TSqlLint has several issues with processing of GO statement

### ISSUE THREAD

**Issue by svasilenko** [tsqllint/tsqllint#207]
**1st issue - does not catch an issue when GO is terminated by semicolon**

D:\_download>type sample1.sql
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT 1 DUMMY;
/* BOTTOM COMMENT */
GO;
D:\_download>tsqllint sample1.sql
Loaded plugin: 'TSQLLint_MC_Plugin.MCPlugin', Version: '0.6.0.0'

Linted 1 files in 0.5748467 seconds

0 Errors.
0 Warnings

Execute sample1.sql
`
Msg 102, Level 15, State 1, Line 7
Incorrect syntax near 'GO'.
`

[T-SQL documentation says](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-2017)
"Do not use a semicolon as a statement terminator after GO."

**2nd issue - GO may follows after last comment block (last comment block rule does not work properly with GO)**

D:\_download>type sample2.sql
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT 1 DUMMY;
/* BOTTOM COMMENT */
GO
D:\_download>tsqllint sample2.sql
Loaded plugin: 'TSQLLint_MC_Plugin.MCPlugin', Version: '0.6.0.0'

Linted 1 files in 0.5573274 seconds

0 Errors.
0 Warnings

**Comment by nathan-boyd** [comment]
For the first issue, although the guidelines state that the "go" batch separator should not be terminated by a semicolon, it's still valid syntax and as such TSQLLint will not identify that as an error.  A new rule could be created that would identify this condition as an error, feel free to make that contribution to the project.

For the second issue It looks like you're using a custom plugin called 'TSQLLint_MC_Plugin.MCPlugin' and its "last comment block" rule isn't performing the way you'd like. I would provide this feedback as an issue in that repository.
