### ISSUE TITLE
Performance issues with large/huge files (?)

### ISSUE THREAD

**Issue by nandaccio** [tsqllint/tsqllint#209]
I tried to run tsqllint by analysing a huge file (2.6GB) and it looked stuck, so I tried with a file with a more reasonable size (80MB). 

tsqllint is running for hours, showing just a blinking text cursor, so I'm not sure if it's stuck in a loop or if I have just to expect this (and wait for the completion...) because of the amount of lines to process: around 69K statements for the 80MB file.

**Comment by nathan-boyd** [comment]
Large file / object size will always be an issue for tools that perform tree parsing, having said that there are improvements that could be made here. For example we could grab the top level script nodes from each file and parse them in parallel.

**Comment by nandaccio** [comment]
Thanks for your feedback. I confirm that there's actually an issue: after more than 24 hours (on a fairly powerful PC) tsqllint is still "stuck" with the 80MB SQL file. That file contains around 69K INSERT statements and there's this blinking text cursor since yesterday.

Is there any way to check if it's actually busy processing the input or if it's just stuck?

**Comment by nandaccio** [comment]
Not sure if it might be useful, but it seems that running TSQLLint.Console.exe (compiled from source code) works as expected:

TSQLLint.Console.exe test.sql
test.sql(18697,20): error invalid-syntax : Incorrect syntax near ]..

Linted 1 files in 7,3123492 seconds

1 Errors.
0 Warnings

While if I do the same using tsqllint installed via npm:

tsqllint test.sql
_ <-- blinking text cursor

Does not work.

**Comment by nathan-boyd** [comment]
That is helpful feedback. It looks like the problem in in the [NodeJS wrapper](https://github.com/tsqllint/tsqllint/blob/master/tsqllint.js) we use to call the TSQLLint Assemblies.

**Comment by nandaccio** [comment]
The issue appears to be related to TSQLLint.Console.exe itself: I ran TSQLLint.Console.exe available under \AppData\Roaming\npm\node_modules\tsqllint\assemblies\win-x64 and it got stuck, then after a couple of minutes I ran also TSQLLint.Console.exe compiled directly from the sources.

As you can see, the first one is stuck, while the second one completed "in just" 9 seconds:
![2019-05-23 12_18_46-C__windows_system32_cmd exe](https://user-images.githubusercontent.com/13116598/58245509-3cf6a500-7d55-11e9-83ff-0d24fd3dfa0a.png)

Test.sql is a sample file with 69K INSERTs, its size is around 80MB.

**Comment by nandaccio** [comment]
The working version of  TSQLLint.Console.exe is the one on the right side: runtime target is .NETCoreApp,Version=v**2.1**/win-x64 (instead of 2.0) and dependencies seem to be slightly more up-to-date.

![2019-05-23 12_27_28-Current - OneNote](https://user-images.githubusercontent.com/13116598/58246039-6237e300-7d56-11e9-87f9-17f0c57f7aee.png)

**Comment by nandaccio** [comment]
The working version of TSQLLint.Console.exe is the one on the right side: runtime target is .NETCoreApp,Version=v2.1/win-x64 (instead of 2.0) and dependencies seem to be slightly more up-to-date.

![2019-05-23 12_27_28-Current - OneNote](https://user-images.githubusercontent.com/13116598/58246282-eee2a100-7d56-11e9-9601-4b7a84d17d6c.png)
