### ISSUE TITLE
Add (line,col,lineend,colend) output to console output to allow range selection

### ISSUE THREAD

**Issue by Tarig0** [tsqllint/tsqllint#210]
This is a request to add two more bits of data to the console output that can be parsed to allow vscode and azure devops to select the range that violates a given rule.

This does not interfere with the integration with SSMS

**Comment by nathan-boyd** [comment]
Can you provide an example of what you mean. What are you seeing, and what would you prefer to see?

**Comment by Tarig0** [comment]
A good example is capitalize key words rule. In the VScode extension there is not enough data to give a range narrowing the focus to just the symbol that is running a fowl of the rule.

**Comment by Tarig0** [comment]
This would be the precursor to this https://github.com/tsqllint/tsqllint-vscode-extension/issues/2
