### ISSUE TITLE
Azure Data Studio Support

### ISSUE THREAD

**Issue by rudeb0y** [tsqllint/tsqllint#211]
Would it be possible to port this to Azure Data Studio?

It's based off VSCode. However it probably also needs ESLint

**Comment by nathan-boyd** [comment]
its definitely possible. also TSQLLint has no dependency on ESLint. TSQLLint just a self contained binary. We use NPM for packaging / distribution, because we didnt like the other options at the time the project was created.

**Comment by Tarig0** [comment]
See https://github.com/tsqllint/tsqllint-vscode-extension/issues/22
