### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by ljmf00** [tsqllint/tsqllint#219]
This rules need documentation:

- [ ] /documentation/rules/named-constraint.md
- [ ] /documentation/rules/schema-qualify.md
- [ ] /documentation/rules/semicolon-termination.md
- [ ] /documentation/rules/select-star.md
- [ ] /documentation/rules/multi-table-alias.md
- [ ] /documentation/rules/set-variable.md
- [ ] /documentation/rules/set-ansi.md
- [ ] /documentation/rules/non-sargable.md
- [ ] /documentation/rules/set-nocount.md
- [ ] /documentation/rules/object-property.md
- [ ] /documentation/rules/print-statement.md
- [ ] /documentation/rules/set-quoted-identifier.md
- [ ] /documentation/rules/upper-lower.md
- [ ] /documentation/rules/set-transaction-isolation-level.md
- [ ] /documentation/rules/unicode-string.md

**Comment by LowlyDBA** [comment]
@nathan-boyd mind if I take a crack at this? 

If so, what are your thoughts on providing outside sources justifying / explaining *why* these rules exist as part of the individual rule docs?

**Comment by nathan-boyd** [comment]
Absolutely and thanks for wanting to contribute. I am open to linking out to other sources, go for it :)
