### ISSUE TITLE
Plugin node doms contain no batches

### ISSUE THREAD

**Issue by WRXRaven** [tsqllint/tsqllint#229]
On master with the DacFx dom lib, plugin integrations do not get the complete script DOM.

**Comment by nathan-boyd** [comment]
@WRXRaven catching back up with the TSQLLint backlog. Is this still an issue?

**Comment by WRXRaven** [comment]
This was related to getting the MC plugin working with the latest verison of the MSFT DOM.  I thought this issue was dependent on the core tsqllint getting built using the newest versions?
