### ISSUE TITLE
Custom Rules using Plugin Handler and external DLL

### ISSUE THREAD

**Issue by tim-parr-workspace** [tsqllint/tsqllint#238]
Hi,

I really like this tool but the inability to create custom rules using the ScriptDom makes it limited. I've got a working version currently that uses the Plugin Handler to pull Rules from a DLL that could also contain plugins.

For Reference: https://github.com/tsqllint/tsqllint/compare/master...tim-parr-workspace:master

**Comment by LowlyDBA** [comment]
This would really increase the extensibility, would love to see this get merged!

**Comment by LowlyDBA** [comment]
Bump

**Comment by LowlyDBA** [comment]
Bump
