### ISSUE TITLE
Publish TSQLLint.Console as a .NET Core tool

### ISSUE THREAD

**Issue by ajhall** [tsqllint/tsqllint#241]
We'd like to use TSQLLint without the dependency on npm, and it seems well-suited to use as a [.NET Core tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool).

Configuring the csproj would be as simple as [this commit](https://github.com/tsqllint/tsqllint/commit/8d3c8fae816a4af9a57a12b615d1095af9464e05), and then just `dotnet pack .\source\TSQLLint.Console\TSQLLint.Console.csproj -c Tool` and push the package up to NuGet.org. .NET Core tools are also cross-platform, so it wouldn't require any multi-platform builds like the current build/package process.

Usage would be something like this:
```bash
dotnet tool install TSQLLint.Console
dotnet tsqllint
```

Let me know if you'd like a pull request to update the csproj. I could update the build and publish scripts too, but I'd need some guidance on how you want that handled.

**Comment by nathan-boyd** [comment]
This would be great. I'll put something together.

**Comment by ajhall** [comment]
Bump to prevent closure. We made our own internal build to get around this, but it would be really nice to have an official .NET Core Tool build.

**Comment by ajhall** [comment]
Bump

**Comment by nathaniel-holder** [comment]
Bump

**Comment by Tanzy** [comment]
bump, any idea if this will be converted into a Net Core Tool?

**Comment by shiitake** [comment]
For anyone who is interested - I've added tsqllint to the community repository for Chocolatey. 
https://community.chocolatey.org/packages/tsqllint/1.11.0

I understand that this is not exactly what you're looking for @ajhall (i.e. cross-platform) but it does remove the NPM dependency.

**Comment by nathan-boyd** [comment]
closing this as implemented in cfa67dadfc7820c5c77ea73a8b622ada8b0e5dc9
