### ISSUE TITLE
inconsistent results depending on the sql compatibility level used

### ISSUE THREAD

**Issue by meredithwryan** [tsqllint/tsqllint#260]
linting the same file, only changing the compatibility level set in .tsqllintrc I get vastly different results.

**Comment by bbelnap** [comment]
I have also noticed this, specifically after recently changing compatibility level to 150. There are scripts that now have syntax errors surrounding temporal tables, JSON, and AT TIME ZONE. I don't get the syntax errors with compatibility level 140.
