### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by ma73i** [tsqllint/tsqllint#263]
Hello! We'd love to use the tool but it seems the npm package does not correspond to the latest code here.
Could you please update the npm version as well?
Thank you in advance.

**Comment by LowlyDBA** [comment]
Same! We would like to implement some of the new rules, but they're not available in the current NPM package.

**Comment by LowlyDBA** [comment]
Bump

**Comment by nathan-boyd** [comment]
this is complete, send any issues my way.
