### ISSUE TITLE
TSQLlint doesn't seem to support sqlcmd vars?

### ISSUE THREAD

**Issue by camjonesatri** [tsqllint/tsqllint#276]
It parses them all as a critical error in my repos wherever they are used

**Comment by nathan-boyd** [comment]
please provide an example query, your tsqllintrc file, and the output you're seeing

**Comment by camjonesatri** [comment]
Sorry I'll close this. I didn't realise there were multiple SQL linters running inside our Codacy.

**Comment by nathan-boyd** [comment]
no worries 👋
