### ISSUE TITLE
Config option spelling: "compatability" vs "compatibility"

### ISSUE THREAD

**Issue by aharpervc** [tsqllint/tsqllint#297]
Hi, I noticed that "compatibility" (t-i-b) is spelled as "compatability" (t-a-b) in the code & readme (I [checked](http://docs.microsoft.com/en-us/sql/relational-databases/databases/view-or-change-the-compatibility-level-of-a-database), and SQL Server docs are also "compatibility").

I assume this is a typo. Would you accept a PR to find/replace as a fix? Besides being a breaking config change, do you foresee any other issues with correcting the naming?

**Comment by olivia-zh-xm** [comment]
I will work on this and submit PR later

**Comment by nathan-boyd** [comment]
Thanks for reporting 👍
