### ISSUE TITLE
Plugin that references other assemblies will not load

### ISSUE THREAD

**Issue by stephenliberty** [tsqllint/tsqllint#322]
Apologies - I am NOT a C# expert by any means and I know some of my vocabulary here is going to be off. 

When building a plugin, if I try and use any outside packages (ex: if I add YamlDotNet), the dll that is built will not load and I get the following error: 

```
There was a problem with plugin: tsqllint_plugin.SamplePlugin - Could not load file or assembly 'YamlDotNet, Version=12.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified
```

Now, I've tried adding the file to the 'gac', I've tried adding the YamlDotNet dll to various folders - no luck. Is this something obvious that I'm missing? Are the plugins incapable of having things added to them?

**Comment by stephenliberty** [comment]
Update: I think I've found the root of the issue. Using [`LoadFile`](https://github.com/tsqllint/tsqllint/blob/main/source/TSQLLint.Infrastructure/Plugins/AssemblyWrapper.cs#L11) apparently will not try to load other dependencies 'normally'. If I change `LoadFile` to `LoadFrom` (which does perform this behavior) the plugin now works. 

Question I've got now is whether I've broken something else by making that change?

**Comment by stephenliberty** [comment]
@nathan-boyd - is there a particular reason that LoadFile was chosen here?

**Comment by nathan-boyd** [comment]
Most plugins just use the SQL DOM and don't have external dependencies.  Plugins with more functionality sounds like a good feature, provided we don't introduce regressions. If LoadFile can meet that bar then it sounds like a good addition to the project.

**Comment by stephenliberty** [comment]
Thanks, @nathan-boyd  - so, I guess the question to you would be "how do I prove it doesn't introduce regressions"? We'd like to see this addition (otherwise I've got to start a fork and keep that up to date which really doesn't sound like fun) and I'm not quite sure where to start. Or whether it's just a matter of bribing the maintainers with coffee or some such.

**Comment by nathan-boyd** [comment]
Pull request tests pass and pre-existing plugins continue to function without having to update.

**Comment by stephenliberty** [comment]
Alright, I made that change - there's no difference to the plugin interface or anything like that. 

https://github.com/tsqllint/tsqllint/pull/323

**Comment by nathan-boyd** [comment]
thanks, will review

**Comment by nathan-boyd** [comment]
Changes have been merged and released in latest version
