### ISSUE TITLE
Consider making easier to use in Script Review process

### ISSUE THREAD

**Issue by geoffbaker** [tsqllint/tsqllint#42]
Until such time this gates check ins, it would be nice to provide a way to easily run tsqllint during script review process. Recently comparison was added as a link directly from google spreadsheet. Something similar for this tool would help.

**Comment by nathan-boyd** [comment]
I think this request would be best served by a shell script that reviewers could use to automate the steps required to copy and reformat their review scripts, such that they can be consumed by our tool. I don't think we want to make any updates to TSQLLINT just to serve this need though. What do you think?
