### ISSUE TITLE
Incorrect semicolon-termination detection

### ISSUE THREAD

**Issue by jmbeach** [tsqllint/tsqllint#43]
Example:

![image](https://user-images.githubusercontent.com/2680142/30500462-061fad3a-9a24-11e7-833b-0720eeffdb0e.png)

Statements of this form say "Statement not terminated with semicolon." even though they are.

**Comment by nathan-boyd** [comment]
Thank you for reporting this. I too have reproduced the behavior and will work towards a fix.

**Comment by nathan-boyd** [comment]
resolved in a5c82b7dd2453856689a7453af1612accad44626

**Comment by jmbeach** [comment]
Awesome!
