### ISSUE TITLE
IDENTITY_INSERT Capitalization not handled correctly

### ISSUE THREAD

**Issue by jmbeach** [tsqllint/tsqllint#44]
`SET IDENTITY_INSERT db.Example ON;`

gives `Expected TSQL Keyword to be capitalized.` at the token `IDENTITY_INSERT` even though it is capitalized.

**Comment by nathan-boyd** [comment]
Thanks for reporting this! This bug occurred because of an improper handling of non alpha chars in our keyword capitalization rule. 

Resolved in f50a749418a26cd73897c03bba8e648d57b55d2f
