### ISSUE TITLE
Linter shouldn't expect semicolons after "BEGIN"

### ISSUE THREAD

**Issue by richSalesforce** [tsqllint/tsqllint#51]
Given the following input, tsqllint outputs an error.
```
IF (1 = 1)
BEGIN
  SELECT 0;
END;
```

The error is:
test.sql(2,7): error semicolon-termination : Statement not terminated with semicolon.

My understanding is that is poor style to put semi-colons after BEGIN, so this error should not appear.

**Comment by nathan-boyd** [comment]
We've been getting a lot of pushback on this issue, I reached out to a few SME's and they agreed that the rule should not require termination of the BEGIN keyword with a semicolon.

**Comment by nathan-boyd** [comment]
resolved in 8b948ac
