### ISSUE TITLE
CrossDb rule fires on LinkedServer

### ISSUE THREAD

**Issue by jamisonr** [tsqllint/tsqllint#52]
We get both CrossDb and LinkedServer errors when a four-part name is encountered. We should only get one of these.

**Comment by nathan-boyd** [comment]
I was thinking about that behavior during development. The rationale was that 4 part names must also be 3 part names but its admittedly confusing. I didn't love it when I put it in, and receiving push back on it is enough for me to alter it. Thanks for the input!

**Comment by nathan-boyd** [comment]
resolved in 4745c6ce4d09b8c05eaae9859bac88f437a4514f
