### ISSUE TITLE
TSQL Lint node pkg expects win32 (not installable on OS X 'darwin')

### ISSUE THREAD

**Issue by charlesstrong** [tsqllint/tsqllint#74]
```
npm i -g tsqllint
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for tsqllint@1.5.0: wanted {"os":"win32","arch":"any"}
(current: {"os":"darwin","arch":"x64"})
```

**Comment by charlesstrong** [comment]
This project is heavily dependent on MS technologies. I believe I can find a different library to accomplish my tasks.

**Comment by nathan-boyd** [comment]
@charlesstrong thanks for checking out TSQLLint, you may be interested in our recent port to dotnet standard aa735a25a011e8491133c360f7020e4d5f0c648a
