### ISSUE TITLE
does not install correctly with old versions of node

### ISSUE THREAD

**Issue by nathan-boyd** [tsqllint/tsqllint#8]
update engines to require latest LTS version of node

**Comment by dougwilson** [comment]
Why? Since this isn't even a node app, it shouldn't matter what version of node is installed?

**Comment by nathan-boyd** [comment]
had a couple report that it wasnt installing correctly on their machines with node .10

**Comment by dougwilson** [comment]
It's likely an npm version requirement vs a node one. Like maybe add engines.npm greater than some version. Probably say greater than or equal to 4.0

**Comment by dougwilson** [comment]
Also, if it is the node.js that was preinstalled on the old et image, the issue i believe is that the PATH does not include the global npm installs, which is a bad install issue.

**Comment by nathan-boyd** [comment]
I was not able to reproduce this behavior, I agree that this is likely related to a bad node installation.
