### ISSUE TITLE
Implement "use strict" feature

### ISSUE THREAD

**Issue by nathan-boyd** [tsqllint/tsqllint#92]
This would allow users to tag their scripts with a "use strict" identifier of some sort that would identify their script as one which should be linted strictly. A strict lint would mean that all rules listed in the config would be enforced as errors, despite their configured error level.

**Comment by dougwilson** [comment]
Since this strict module is specific to the linting it should probably be very similar to the comments for overriding rules.

**Comment by dougwilson** [comment]
Perhaps

    /* tsqllint-strict */
